# Generated by Django 5.2.5 on 2025-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="birth",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique_for_date="published"
            ),
        ),
    ]
