# Generated by Django 5.2.6 on 2025-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20250915_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birth",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique_for_date="date"),
        ),
    ]
