# Generated by Django 5.2.6 on 2025-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_birth_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="birth",
            name="anon_id",
            field=models.UUIDField(null=True),
        ),
    ]
