# Generated by Django 5.2.7 on 2025-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_birth_anon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birth",
            name="religion",
            field=models.TextField(
                default="Unknown",
                help_text="Enter your religion info and where you were born",
            ),
        ),
    ]
