# Generated by Django 5.2.7 on 2025-10-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="Class",
            new_name="class_number",
        ),
    ]
