# Generated by Django 5.2.7 on 2025-10-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_education_created_at_education_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_socials",
                to="data.social",
            ),
        ),
    ]
