# Generated by Django 5.2.7 on 2025-10-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_education_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="social",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_socials",
                to="data.social",
            ),
        ),
    ]
