# Generated by Django 5.2.7 on 2025-10-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_alter_education_social"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="social",
        ),
    ]
