# Generated by Django 5.2.7 on 2025-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_alter_company_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="total_workers",
            field=models.IntegerField(help_text="Total number of employees working"),
        ),
    ]
